### ISSUE TITLE
[ENH] Support for localized (locale) names

### ISSUE THREAD

**Issue by Wabbit0101** [quat1024/simpletrophies#3]
Add option to support equivalent of "LocName" so that the trophy picks up a string from a lang file for displaying. This allows modpacks/maps/etc. to give trophies with localized strings.

**Comment by quat1024** [comment]
I believe it already does

**Comment by Wabbit0101** [comment]
Oh, so the 'TrophyName' field is a lang file key and not the actual display text? (It looks like the display text from the wiki's example...)

**Comment by quat1024** [comment]
You can use it either way!
