### ISSUE TITLE
Where is the config file?

### ISSUE THREAD

**Issue by Winddbourne** [quat1024/simpletrophies#4]
I made my first trophy using the magic creative mode method . . . and it's great for what I want to use it for. I'm going to make it a quest turn in key and give a copy of my current inventory to players complete with the date I earned the thing. Players will 100% not be able to duplicate the key. 

But I was looking for the configuration code where I'd place my info from the clipboard if I wanted to hand out trophies normally, or where I would go to input my NBT hacker data.  Do I have to put this in the scripts folder like my zenscript stuff or something? 

I'd like to know in case I use the trophies later for other things . . . say rewards for completing quests where I really do want it to display the right date/time/etc . . . lol

**Comment by quat1024** [comment]
There's no config file - any way of giving players items with NBT data will do. Quest rewards, advancements (probably), Triumph, just plain ol recipes, commands, what-have-you.

You could look at the modpack FTB Interactions for an example of handing out trophies as quest rewards - I don't know how to do it myself, I don't have any experience using questing mods myself lol.

**Comment by Winddbourne** [comment]
Well, that's different. I know how to do this I just have to edit the
better questing file to remove the date NBT tag, I won't even need to have
anything in the clipboard . . . but if I'd had to resort to this without
talking to you I would think I'd missed something and was hacking a
workaround for my own ignorance. You might want to make this clear in the
description since the presence of the "magic" creative mode method makes a
user think that anybody should be able to use this without actually knowing
NBT or Zenscript, or what a JSON file is. I was actually expecting some
sort of command in-game or at the very least a config file where a complete
computer illiterate could paste his newly created trophy.

It's easy for me . . . but I'm used to using Biometweaker, Gamestages,
Crafttweaker, and JustEnoughDimensions in my packs. That isn't likely to be
true for someone who needs the magic creative method. I only used it
because I'm doing enough coding already and wanted to do things the easy
way for once. lol

**Comment by quat1024** [comment]
The point of using creative mode is so when you right-click in the air with the trophy it copies the nbt tag to your clipboard for you to do whatever you want with. You can also use `/mt hand` I suppose. I just added it because i got sick of using `/blockdata` to edit a trophy

**Comment by quat1024** [comment]
I can't add a config file anyways. I don't know what methods you want players to earn the trophies with. Like what would I even put in the config file

**Comment by Winddbourne** [comment]
What I would do in your place is to somehow have the mod add trophies with
meta-data to the list of objects in Minecraft so it shows up in the
JEI/creative menu as an item with no recipe. You right click your trophy in
the air and it sends the data into a config file rather than onto the
clipboard with a little message to reload the game to access your trophy.

I'm using Enchiridion to write books now and it does things that way. You
have a starter book object that you click on to activate book creation and
when you reload your game suddenly your book pops up as one of the assets
loaded by the mod. Initially, I thought that having to reload the game was
a bit unintuitive but it's the best book-making mod I've found. The in-game
editor is so easy to use.  Sure we could just use MT hand with Crafttweaker
but that requires players to download a separate mod. Plus a lot of times
translating the tags from Zenscript format takes a bit of effort.
CraftTweaker, Better Quests, and custom starter gear all store the data
differently.

I actually had to add custom starter gear instead of just using void island
control because that program's automatic config set up couldn't figure out
how to translate an item's tags into its format and neither could I.  It
kept giving me the basic Enchiridion starter book no matter what guide I
wanted players to have at start. The program always wanted to cut off all
the tags. Which isn't a problem with the mod Bartz is amazing and Void
Island Control is the best sky world generator I've found; it's just not a
dedicated starting inventory mod and had trouble with more advanced tags.

I hope the feedback helps. :)

**Comment by Winddbourne** [comment]
I just looked at the update data and even though I haven't checked out the config file yet I wanted to come back to this topic and say thank you. Its always nice to see an update that takes my concerns into account, and I know that hard working mod makers don't often hear positive reactions as often as they should.

👍
