### ISSUE TITLE
Crash with Creative Wireless Terminal Trophy in Hand

### ISSUE THREAD

**Issue by IcedReaper** [quat1024/simpletrophies#6]
Hi,

I tried to add a Trophy for the Creative Wireless Ultimate Terminal of the Mod "AE2 Wireless Terminal Library".
When I have the Trophy in my Inventory and hover with the cursor over it the Game crashes.

Crash Log: https://pastebin.com/mjmj62P5

I don't know if the "real" error is on your or @p455w0rd's end.
I think it would be great if there would be an NBT-Tag to disable the original Tooltip for a trophy (it could be enabled by default or when the NBT-Tag isn't available) or at least have an configs option to disable the original Tooltip globally.

Thanks in Advance.
IcedReaper

**Comment by quat1024** [comment]
Uh oh!

I'll add a try-catch around the tooltip code in case it blows up, and add a config option to hide the tooltip anyways (maybe even a per-trophy option, depends if I can remember how to add those) (sorry this codebase is really crappy)

**Comment by quat1024** [comment]
Should be fixed in 1.2.2(.1) which was just approved on curse ;0 https://www.curseforge.com/minecraft/mc-mods/simple-trophies/files/2863053

**Comment by IcedReaper** [comment]
Thank you for the fast fix. I just tried it and it works like a charm.
